core/aws_ddk_core/cicd/pipeline.py
core/aws_ddk_core/pipelines/pipeline.py
core/aws_ddk_core/pipelines/stage.py
core/aws_ddk_core/resources/_kms.py
core/aws_ddk_core/resources/_lambda.py
core/aws_ddk_core/resources/_s3.py
core/aws_ddk_core/resources/_sqs.py
core/aws_ddk_core/stages/glue_transform.py
core/aws_ddk_core/stages/s3_event.py
core/aws_ddk_core/stages/sqs_lambda.py
docs/.gitignore
docs/index.markdown
docs/source/_templates/custom-class-template.rst
docs/source/cli/aws_ddk.rst
docs/source/core/aws_ddk_core.rst
docs/source/index.rst

- Refactoring
- Refactored the docs structure to leverage Sphinx templates and the ability to showcase nested methods
- By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Restructure the docs

---

.github/workflows/git-hygiene.yml

Reference: https://github.com/actions/stale

Adding Stale Issue Workflow

---

core/aws_ddk_core/pipelines/__init__.py
core/aws_ddk_core/pipelines/state_machine_stage.py
core/aws_ddk_core/resources/__init__.py
core/aws_ddk_core/resources/_sfn.py
core/aws_ddk_core/stages/glue_transform.py
core/tests/unit/conftest.py
core/tests/unit/test_basic_data_pipeline.py
core/tests/unit/test_glue_transform_stage.py
core/tests/unit/test_sfn.py
docs/source/core/aws_ddk_core.rst

- Feature
- Add state machine factory
- Add state machine stage with a few helpers, defined event pattern and target
- Refactor GlueTransformStage to use state machine stage as base
- #26 

(core ) add step function stage & step function factory

---

cli/aws_ddk/__main__.py
cli/aws_ddk/commands/create.py
cli/aws_ddk/commands/init.py
cli/aws_ddk/utils.py
cli/tests/unit/test_cli.py
core/aws_ddk_core/stages/sqs_lambda.py

- Enhancement
- Add `git configure` commands to `ddk create-repository` CLI
- #38

(cli): Improve git commands in create-repository

---

cli/aws_ddk/__metadata__.py
cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/pyproject.toml
core/aws_ddk_core/__metadata__.py
core/aws_ddk_core/cicd/pipeline.py
core/pyproject.toml
docs/_site/source/conf.py
docs/source/conf.py
docs/source/core/aws_ddk_core.rst
pyproject.toml
setup.cfg

- Release
- Bump version to 0.2.0

Prepare release 0.2.0

---

core/aws_ddk_core/stages/__init__.py
core/aws_ddk_core/stages/athena_sql.py
core/tests/unit/test_athena_sql_stage.py
core/tests/unit/test_basic_data_pipeline.py
docs/source/core/aws_ddk_core.rst

(core) add Athena SQL stage

---

core/aws_ddk_core/cicd/__init__.py
core/aws_ddk_core/cicd/_utils.py
core/aws_ddk_core/cicd/actions.py
core/tests/unit/test_cicd_pipeline_stack.py

- Feature
- Add action to build wheel and publish it to CodeArtifact repository
- #52 

(core) add CodeArtifact publish action

---

cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/aws_ddk/data/project_templates/ddk_app/{{cookiecutter.directory_name}}/ddk.json
cli/aws_ddk/data/project_templates/ddk_app/{{cookiecutter.directory_name}}/requirements.txt
core/poetry.lock
core/pyproject.toml

- Feature
- Our constructs will break in newer CDK versions especially alpha packages
- Bootstrap version is fixed
- We have to update template CDK version every time we update
- N/A

Pin CDK library version

---

core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_sqs_lambda_stage.py

- Feature
- add lambda layers arg to sqs-lambda stage
- N/A

(core) add lambda layers arg to sqs-lambda stage

---

core/aws_ddk_core/pipelines/pipeline.py
core/aws_ddk_core/pipelines/stage.py
core/aws_ddk_core/stages/__init__.py
core/aws_ddk_core/stages/appflow_ingestion.py
core/aws_ddk_core/stages/athena_sql.py
core/aws_ddk_core/stages/glue_transform.py
core/aws_ddk_core/stages/kinesis_s3.py
core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_appflow_stage.py
core/tests/unit/test_basic_data_pipeline.py
core/tests/unit/test_sqs_lambda_stage.py
docs/source/core/aws_ddk_core.rst

- Enhancement
- Suggest renaming `AppFlowStage` to `AppFlowIngestionStage` as it's more explicit and leaves the door open for other AppFlow stages in the future
- Add alarms to all SFN based stages

(core): Add state machine alarms and rename AppFlow stage

---

core/aws_ddk_core/stages/appflow_ingestion.py
core/aws_ddk_core/stages/athena_sql.py
core/aws_ddk_core/stages/glue_transform.py
core/tests/unit/test_basic_data_pipeline.py

- Enhancement
- Expose the state machine objects in DDK data stages

(core): Expose state machine objects in stages

---

core/aws_ddk_core/stages/appflow_ingestion.py
core/aws_ddk_core/stages/athena_sql.py
core/aws_ddk_core/stages/glue_transform.py

- Feature
- adding ability to add more state machine role policies - existing ones are very opinionated and not convenient to extend
- n/a

(core) add additional_role_policy_statements to state machine stages

---

.github/workflows/docs-release.yml

- Adds additional action to docs release workflow to tag stable version to newest released version
- #84 

(docs) updating documentation release workflow to tag stable release

---

cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
core/aws_ddk_core/resources/_s3.py
core/aws_ddk_core/stages/kinesis_s3.py
core/aws_ddk_core/stages/s3_event.py
core/poetry.lock
core/pyproject.toml
core/tests/unit/test_basic_data_pipeline.py

- Feature
- Add event_bridge_enabled to bucket factory
- Remove CloudTrail from S3EventStage
- Update event patterns on S3EventStage & Kinesis stage
- Update CDK version
- N/A

(core|cli) enable EventBridge notifications; remove CloudTrail; update CDK version

---

cli/aws_ddk/__metadata__.py
cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/pyproject.toml
core/aws_ddk_core/__metadata__.py
core/aws_ddk_core/stages/kinesis_s3.py
core/pyproject.toml
docs/_site/source/conf.py
docs/source/conf.py
pyproject.toml
setup.cfg

- Bug in Firehose Stage
- Bug fixed
- 0.3.0 -> 0.3.1
- <URL or Ticket>

(version) bumping to 0.3.1 with fix 

---

docs/release/next/how-to/ddk-configuration.markdown

(docs) how-to guide ddk configuration

---

core/aws_ddk_core/pipelines/stage.py
core/tests/unit/test_basic_data_pipeline.py

- Feature
- Add ability to do `s3_event_stage >> sqs_lambda_stage >> glue_stage`

(core) add stage rshift operator

---

CONTRIBUTING.md
README.md
docs/release/next/how-to/private-artifactory.markdown

- Docs
- Add How-To guide on creating a CodeArtifact private domain
- Clarify how to create a test environment
- Add learning resources to README
- #80

(docs): How-To Private Code Artifact and other enhancements

---

cli/aws_ddk/data/project_templates/ddk_app/{{cookiecutter.directory_name}}/requirements.txt

- Bugfix
- Add alpha packages to cli requirements.txt template
- #106 

Add alpha packages to cli requirements.txt template

---

core/aws_ddk_core/resources/__init__.py
core/aws_ddk_core/resources/_dms.py
core/aws_ddk_core/stages/__init__.py
core/aws_ddk_core/stages/dms_s3_to_s3.py
core/tests/unit/conftest.py
core/tests/unit/test_dms.py
core/tests/unit/test_dms_stages.py

- DMS Ingestion Stage 
- DMSFactory
- DMS S3 to S3 Stage (pending validation of functionality)
- #89 

(core) dms ingestion stage

---

cli/aws_ddk/__metadata__.py
cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/pyproject.toml
core/aws_ddk_core/__metadata__.py
core/pyproject.toml
docs/_site/source/conf.py
docs/source/conf.py
pyproject.toml
setup.cfg

Release 0.5.1

---

API.md
src/cicd/actions.ts
src/cicd/pipelines.ts

Support local package path install in CICD synth action pre-public release

feat: Support local package path install in CICD synth action pre-public release

---

core/aws_ddk_core/stages/glue_transform.py
core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_glue_transform_stage.py
core/tests/unit/test_sqs_lambda_stage.py

- Stages `SqsToLambdaStage`, `GlueTransformStage` Additional resource level args
- 
- Adds `glue_job_args` & `glue_crawler_args` to `GlueTransformStage`
- Adds `function_props` to `SqsToLambdaStage`
- #169 

Enhancement: Stages `SqsToLambdaStage`, `GlueTransformStage` Additional resource level args

---

core/aws_ddk_core/stages/s3_event.py
core/tests/unit/test_s3_event_stage.py

- Support Multiple S3 Prefixes in S3 Event Stage

Enhancement: Support Multiple S3 Prefixes in S3 Event Stage

---

core/aws_ddk_core/stages/glue_transform.py

- `GlueTransformStage`: Make crawler state pass to Succeed not Fail

`GlueTransformStage`: Make crawler state pass to `Succeed` not `Fail`

---

cli/aws_ddk/__metadata__.py
cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/pyproject.toml
core/aws_ddk_core/__metadata__.py
core/pyproject.toml
docs/_site/source/conf.py
docs/source/conf.py
pyproject.toml
setup.cfg

Bump Version`0.5.1` -> `0.6.0`

---

README.md

(docs) Add DDK value prop to README

---

cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
core/poetry.lock
core/pyproject.toml

CDK Library Upgrade -> 2.54

---

cli/aws_ddk/__metadata__.py
cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/pyproject.toml
core/aws_ddk_core/__metadata__.py
core/pyproject.toml
docs/_site/source/conf.py
docs/source/conf.py
pyproject.toml
setup.cfg

Release: 0.6.1

---

core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_sqs_lambda_stage.py

- adding `queue_props` to `SqsToLambda`
- test to cover the enhancement

Enhancement: adding `queue_props` to `SqsToLambda`

---

core/aws_ddk_core/pipelines/stage.py
core/aws_ddk_core/stages/appflow_ingestion.py
core/aws_ddk_core/stages/athena_sql.py
core/aws_ddk_core/stages/databrew_transform.py
core/aws_ddk_core/stages/glue_transform.py
core/tests/unit/test_appflow_stage.py
core/tests/unit/test_athena_sql_stage.py
core/tests/unit/test_databrew_transform_stage.py
core/tests/unit/test_glue_transform_stage.py

- Adding additonal sfn props support to `StateMachineStage`
- Add test case 

Enhancment: Adding additonal sfn props support to `StateMachineStage`

---

core/aws_ddk_core/resources/_utils.py

**BugFix**
- Fix bug for context_layer undefined error
- Fix bug for region_name error as it was resolved to a token and boto3 expects a string, changed behavior to derive from boto3 session

Fix bug for context_layer undefined and changing region_name derived from boto3 session

---

src/cicd/actions.ts
src/cicd/pipelines.ts
src/cicd/utils.ts
src/core/kinesis-firehose-defaults.ts
src/core/s3-defaults.ts
src/pipelines/pipelines.ts
src/stages/sqs-lambda.ts

- Refactoring
- Change the imports to make it clear which objects come from which AWS service

chore: Refactor imports to make the AWS service clear

---

API.md
src/pipelines/stage.ts
src/stages/athena-sql.ts
src/stages/glue-transform.ts

- Refactoring
- Refactor creation of state machine to rely on interface rather than array deconstruction

chore: Refactor creation of state machine

---

API.md
src/stages/databrew-transform.ts
src/stages/index.ts
test/databrew-transform-stage.test.ts

- Adds DataBrewTransformStage
- 100% covered 🧪
- Closes #157 

feat: `DataBrewTranformStage`

---

API.md
src/pipelines/pipelines.ts
test/data-pipelines.test.ts

-  Add `schedule` support to `DataPipeline.add_stage()`
-  Test
- Closes #197 

feat: Add `schedule` support to `DataPipeline.add_stage()`

---

API.md
src/cicd/pipelines.ts
src/stages/sqs-lambda.ts
test/athena-sql-stage.test.ts
test/cicd-pipeline-stack.test.ts
test/data-pipelines.test.ts
test/glue-transform-stage.test.ts
test/sqs-lambda-stage.test.ts

- Increase Coverage to 
- Closes #213 
**Note**: Uncovered lines are either hard or impossible to access in current state without some refactoring. 

chore: Increase Coverage of TS tests

---

CONTRIBUTING.md

chore: Add `CONTRIBUTING.md`

---

package-lock.json
src/stages/glue-transform.ts
yarn.lock

- Refactoring
- Replace CustomTask with CallAwsService in GlueTransform stage

feat: Replace CustomTask with CallAwsService in GlueTransform stage

---

cli/aws_ddk/__metadata__.py
cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/pyproject.toml
core/aws_ddk_core/__metadata__.py
core/pyproject.toml
docs/_site/source/conf.py
docs/source/conf.py
pyproject.toml
setup.cfg

Preparing patch release `0.6.2`

Prepare Release 0.6.2

---

API.md
integ/integ.sns-lambda.test.ts
src/core/sns-defaults.ts
src/stages/index.ts
src/stages/sns-lambda.ts
test/sns-lambda-stage.test.ts

feat: sns to lambda stage

---

integ/integ.appflow-ingestion.test.ts
integ/integ.cicd-pipeline.test.ts
integ/integ.data-pipelines.test.ts
integ/integ.kinesis-s3-stage.test.ts
integ/integ.s3-event.test.ts

chore: Integration fix s3 removal policy

---

API.md
src/stages/glue-transform.ts
test/glue-transform-stage.test.ts

- syncing `GlueTransformStage` to `main`
- Closes #261 

feat: syncing `GlueTransformStage` to `main`

---

API.md
src/stages/athena-sql.ts
test/athena-sql-stage.test.ts

-  syncing `AthenaSqlStage` to `main`
- Closes #263

feat: syncing `AthenaSqlStage` to `main`

---

src/config/configurator.ts

fix: `getConfigAttribute` condition

---

integ/integ.glue-transform.test.ts
src/core/glue-defaults.ts

- Remove whitespace from sec configuration Id
- Closes #274 

fix: Remove whitespace from glue job sec configuration Id

---

API.md
integ/integ.cicd-pipeline.test.ts
src/base/stack.ts
src/cicd/pipelines.ts
test/base-stack.test.ts
test/cicd-pipeline-stack.test.ts

fix: cicd environment support

---

src/config/configurator.ts
test/config.test.ts

fix: static method `Configurator.getEnvConfig()`

---

src/config/configurator.ts
test/config.test.ts

feat: configuration by resource ids

---

core/aws_ddk_core/resources/_lambda.py

bug: Lambda Factory creating vpc configuration regardless of argument

---

docs/release/latest/how-to/custom-stage.markdown

- Documentation
- Fix IDs in custom stage tutorial

chore: Fix IDs in custom stage tutorial

---

docs/release/latest/how-to/multi-account-deployment.markdown

- Documentation
- Fix the code snippets for multi account deployments

chore: Fix the code snippets for multi account deployments

---

docs/_layouts/default.html
docs/index.markdown
docs/release/latest/how-to/upgrade-guide.markdown
integ/integ.athena-sql.test.ts

- Fixing property type for athenasql stage integration test

fix: athena integration test

---

.projenrc.js
docs/_config.yml
docs/_layouts/default.html
docs/workshops.markdown

- Adds `Workshops` page to docs
- Addd SDLF workshop

chore: Adding SDLF workshop and workshops page to docs

---

API.md
README.md

chore: Adds pypi downloads badge and package links to readme

---

API.md
src/core/index.ts
src/core/mwaa-environment.ts
test/mwaa-environment.test.ts

- Changing name to be more accurate and descriptive. `AirflowDataPipeline` can hopefully be a future extension of `DataPipeline`

chore: changing airflow construct name to `MWAAEnvironment`

---

.projen/deps.json
.projenrc.js
API.md
integ/integ.airflow-pipeline.test.ts
package.json
yarn.lock

- Updates cdk version
- Fixes broken integration test

chore: housekeeping

---

package-lock.json
yarn.lock

Fixes [AWS CDK EKS overly permissive trust policies](https://github.com/awslabs/aws-ddk/security/dependabot/30)
-updating cdk for CVE-2023-35165

chore: Security Remediation

---

.github/workflows/upgrade-main.yml
API.md
src/cicd/actions.ts
src/cicd/pipelines.ts
test/cicd-pipeline-stack.test.ts

feat: adding `env` to synth action props

---

API.md
src/core/emr-serverless-cluster.ts
src/core/index.ts
test/emr-serverless-cluster.test.ts

feat: New Construct `EMRServerlessCluster`

---

.projenrc.js
package.json

Adds package metadata including `description` and `keywords`

chore: update package metadata

---

API.md
src/config/configurator.ts

Closes #417 
Allowing `any` in `Configuration.props`

feat: Allowing 'any' in configuration props

---

API.md
src/cicd/pipelines.ts
test/cicd-pipeline-stack.test.ts

feat(cicd): adding install commands

---

package-lock.json
yarn.lock

chore: update dependencies

---

package-lock.json
yarn.lock

Fixes [Vulnerability](https://github.com/awslabs/aws-ddk/security/dependabot/53)

chore: update semver vulnerability

---

.projen/deps.json
.projenrc.js
API.md
package.json
test/cicd-pipeline-stack.test.ts
yarn.lock

Upgrades `aws-cdk-lib` 
- `2.85.0->2.117.0`

chore: upgrade aws-cdk-lib

---

.github/workflows/build.yml
.github/workflows/upgrade-main.yml
.projen/tasks.json
package-lock.json
package.json
yarn.lock

chore: projen upgrade
