cli/aws_ddk/__metadata__.py
cli/aws_ddk/data/project_templates/ddk_app/cookiecutter.json
cli/aws_ddk/data/project_templates/ddk_app/{{cookiecutter.directory_name}}/app.py
cli/aws_ddk/data/project_templates/ddk_app/{{cookiecutter.directory_name}}/requirements.txt
cli/aws_ddk/data/project_templates/ddk_app/{{cookiecutter.directory_name}}/setup.py
cli/pyproject.toml
cli/setup.cfg

- Bugfix
- requirements.txt is pointing to the CLI ddk version when it should be pointing to core
- By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Fix wrong ddk core version in requirements.txt

---

cli/aws_ddk/data/project_templates/ddk_app/{{cookiecutter.directory_name}}/test.sh
core/aws_ddk_core/cicd/__init__.py
core/aws_ddk_core/cicd/actions.py
core/aws_ddk_core/cicd/pipeline.py
core/tests/unit/test_cicd_pipeline_stack.py

- Adding Security Lint Stage `add_security_lint_stage()`
- Adding Tests Stage `add_test_stage()`
- Adding Checks method to add both above stages `add_checks()`
- PyTest for full pipeline example with above methods in instantiation
- [#28 ](https://github.com/awslabs/aws-ddk/issues/28)

add security checks and test stages to CICD pipeline construct

---

core/aws_ddk_core/pipelines/__init__.py
core/aws_ddk_core/pipelines/pipeline.py
core/aws_ddk_core/pipelines/stage.py
core/aws_ddk_core/stages/glue_transform.py
core/aws_ddk_core/stages/s3_event.py
core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_basic_data_pipeline.py

- Refactoring: Rename DDK Stage and Pipeline classes to DataStage and DataPipeline
- Renames DDK `Stage` and `Pipeline` classes to `DataStage` and `DataPipeline`
- https://github.com/awslabs/aws-ddk/issues/32

minor: updating pipeline and stage names to data*

---

.github/workflows/static-checking.yml
cli/aws_ddk/services/cfn.py
cli/aws_ddk/services/codecommit.py
cli/aws_ddk/utils.py
cli/poetry.lock
cli/pyproject.toml
poetry.lock
pyproject.toml
validate.sh

Feature
In order to have type checking for `boto3`-related code, I added `boto3-stubs-lite` library. I did not make any changes in the code, looks like there are no typing issues. But it could be helpful to have type checking for `boto3` anyway.

Add type checking for boto3

---

cli/aws_ddk/__main__.py
cli/aws_ddk/commands/init.py

- Feature
- initialize a git repository when using `ddk init`
- add optional argument `--generate-only`.  This flag skips the git repo and python virtual env steps when set. This mimics behavior from the cdk: https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/init.ts#L273
- #27 

(cli): Initialize a git repository when using ddk init

---

core/aws_ddk_core/cicd/pipeline.py
core/tests/unit/test_cicd_pipeline_stack.py

- Adding method `add_notifications()` to `aws_ddk_core.cicd.pipeline` 
- Adds event rule for failed pipeline events
- Adds sns topic for notifications if not specified in config
- Adds method to full test [tests/unit/test_cicd_pipeline_stack.py::test_cicd_pipeline_full](./core/tests/unit/test_cicd_pipeline_stack.py::test_cicd_pipeline_full)

(core): cicd pipeline alerting

---

core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_sqs_lambda_stage.py

- Adding escape hatch for `aws_ddk_core.stages.SqsToLambdaStage`
- Add arguments to `aws_ddk_core.stages.SqsToLambdaStage`
- **lambda_function**: Optional[IFunction]
Preexisting Lambda Function to use in stage. `None` by default
- **sqs_queue**: Optional[IQueue]
Preexisting SQS Queue  to use in stage. `None` by default
- Unit tests to validate the above arguments.
- `test_sqs_lambda_stage.py::test_sqs_lambda_with_existing_function`
- `test_sqs_lambda_stage.py::test_sqs_lambda_with_existing_queue`
- #46 

(core) adding escape hatches for sqs_lambda stage

---

cli/aws_ddk/__main__.py
cli/aws_ddk/commands/create.py
cli/aws_ddk/commands/deploy.py

- Bugfix
- DDK cli is using `default` profile when none is supplied. This is bad behavior as there are [other ways](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials) to set up a botocore session which do not rely on an AWS Profile. Instead we are assuming that `default` should be used if the user did not provide one, when in fact they could be using env variables or assuming a role provider in SSO
- #60

(cli): Remove default AWS profile

---

core/aws_ddk_core/stages/s3_event.py
core/aws_ddk_core/stages/sqs_lambda.py

- Enhancement
- At the moment, a DDK S3Event Stage creates a CloudTrail Trail and associated Bucket with no way to disable this feature. This fix introduces an escape hatch for the Trail

(core): Add Trail escape hatch to S3 Event Stage

---

core/aws_ddk_core/stages/__init__.py
core/aws_ddk_core/stages/appflow.py
core/aws_ddk_core/stages/lambda_handlers/appflow_check_flow_status/lambda_function.py
core/tests/unit/test_appflow_stage.py
core/tests/unit/test_basic_data_pipeline.py
docs/source/core/aws_ddk_core.rst

(core) add appflow stage

---

core/aws_ddk_core/pipelines/pipeline.py
core/aws_ddk_core/pipelines/stage.py
core/aws_ddk_core/stages/kinesis_s3.py
core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_basic_data_pipeline.py

- Enhancement
- Current DDK Stage CW alarm implementation is limiting the user to one alarm. This PR extends the logic to multiples alarms, providing flexibility to the user to add as many as they wish

(core): Allow multiple cw alarms per stage

---

core/aws_ddk_core/base/stack.py
core/aws_ddk_core/cicd/pipeline.py

Adds documentation of available configuration attributes to `BaseStack` and `CICDPipelineStack` classes.
- #88

(docs) expose configuration attributes for classes in documentation 

---

cli/aws_ddk/commands/deploy.py

- Bugfix
- Add missing --all flag to ddk deploy
- #110

(cli): Add --all to ddk deploy

---

core/aws_ddk_core/resources/_glue.py

- Bugfix
-  remove glue log encryption from default security config
-  #124 

(core) remove Glue log encryption by default from security config

---

cli/aws_ddk/__main__.py
cli/aws_ddk/commands/deploy.py

- Add argument for `ddk deploy` to allow explicitly setting stacks to deploy
- `ddk deploy StackA StackB`
- #121 

(cli) add 'stacks' argument for 'ddk deploy'

---

.projenrc.js
API.md
src/index.ts
src/pipelines/index.ts
src/pipelines/pipelines.ts
src/pipelines/stage.ts
src/stages/index.ts
src/stages/sqs-lambda.ts
test/data-pipelines.test.ts
test/hello.test.ts
test/sqs-lambda-stage.test.ts

- Created `Stage`, `DataStage` and `DataPipeline` constructs in TypeScript CDK
- Created `SQSToLambda` stage in TypeScript CDK
- Added unit tests for the data pipeline and the `SQSToLambda` stage
https://github.com/awslabs/aws-ddk/issues/135

feat: Created DataStage, DataPipeline and SQSToLambda constructs

---

API.md
src/pipelines/pipelines.ts
src/pipelines/stage.ts
src/stages/index.ts
src/stages/s3-event.ts
test/data-pipelines.test.ts
test/s3-event.test.ts

- Feature
- Refactor
- Implemented `S3EventStage`
- Created unit tests for `S3EventStage`
- Refactored DataPipeline to accept `Stage` objects rather than just `DataStage`
- Added a unit test for `DataPipeline` to ensure stages without a target (like `S3EventStage`) aren't declared in the middle of the data pipeline without an explicitly defined rule.
Closes https://github.com/awslabs/aws-ddk/issues/142

feat: Implement S3EventStage in Typescript

---

API.md
src/base/index.ts
src/base/stack.ts
src/index.ts
test/base-stack.test.ts

- Feature
- Refactoring
Implementing `BaseStack` in Typescript CDK. The new stack does not include the `environmentId` yet, as it related to  the config portion, which we haven't implemented yet.
- Closes https://github.com/awslabs/aws-ddk/issues/140

feat: Implement BaseStack in Typescript

---

.github/workflows/build.yml
.mergify.yml
.projen/deps.json
.projen/tasks.json
.projenrc.js
API.md
package.json
yarn.lock

- Upgraded CDK version to `v2.34.0`
- Added configuration for JSII to generate Python objects
- Changed module name to `aws-cdk-core`, to reflect the name of the Python package.

feat: Add support for Python in JSII and upgrade CDK version

---

.projenrc.js

The `.projenrc.js` definition has some duplicate dependency definitions from a previous merge.

chore: Cleaning up .projenrc.js from duplicate dependency definitions

---

core/aws_ddk_core/cicd/pipeline.py
core/tests/unit/test_cicd_pipeline_stack.py

- Fixing unused param: `pipeline_name`
#158 

(core) CICD `pipeline_name`

---

API.md
src/cicd/actions.ts
src/cicd/pipelines.ts

- Making install commands in the synth action stage optional as these may change in different languages and not be necessary all of the time.
- Python implementation requires `[]` in most cases while Typescript requires `[npm install]`

fix: CICD: Presynth install commands -> optional

---

core/aws_ddk_core/stages/glue_transform.py

- GlueTransformStage does not pass crawler name in to SFN

bug: GlueTransformStage does not pass crawler name in to SFN

---

core/aws_ddk_core/stages/s3_event.py
core/tests/unit/test_s3_event_stage.py

- `S3 Event Stage`: Support Multiple Buckets
- Allow a list of buckets passed to `bucket_name`

`S3 Event Stage`: Support Multiple Buckets

---

core/aws_ddk_core/cicd/pipeline.py
core/aws_ddk_core/pipelines/pipeline.py
core/tests/unit/test_cicd_pipeline_stack.py

- Add `add_wave` support to `CICDPipelineStack` construct
- `add_wave()` allows the user to create parallel CDK deployment stages in parallel which will help support cases with several independent cdk stacks managed in one CI/CD pipeline.

Feature: Add `add_wave` support to `CICDPipelineStack` construct

---

cli/aws_ddk/commands/deploy.py
cli/aws_ddk/sh.py

- #178 
- Windows as opposed to POSIX is not able to find `cdk` within a `subprocess.Popen`, but _**is**_ able to find `cdk.CMD`. 
- Windows does not appear to work with `text=False` in [`subprocess.Popen`](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module) for this use case and errors with [this error](https://github.com/awslabs/aws-ddk/issues/178#issuecomment-1294035914). By setting stdout to text not bytes we seem to be able to avoid this issue in the case of a Windows OS. 

Bug: Windows `ddk deploy` Issue

---

core/aws_ddk_core/cicd/pipeline.py
core/tests/unit/test_cicd_pipeline_stack.py

- Support additional pipeline attributes  in `CICDPipelineStack` construct
- Add arg `pipeline_args` to `CICDPipelineStack` to pass in any additional args to the `CodePipeline` in our `build()` method.
- #182 

Enhancment: Support additional pipeline attributes  in `CICDPipelineStack` construct

---

core/aws_ddk_core/stages/sqs_lambda.py
core/tests/unit/test_sqs_lambda_stage.py

- `SqsToLambdaStage` Adding support for fifo event target 
- Adding argument `message_group_id` which is required to set up an SQS event target when the queue is a **_fifo_** queue.
- #183 

Enhancement: `SqsToLambdaStage` Adding support for fifo event target 

---

core/aws_ddk_core/stages/athena_sql.py
core/tests/unit/test_athena_sql_stage.py

AthenaSQLStage to handle both static and dynamic SQL Queries
Stage Enhanced to support both Static Queries (current case) and dynamic queries using statemachine json path to add the ability to run multiple queries using the same state machine
(core): Athena_SQL Stage Update #203

Enhancing AthenaSQLStage to handle both static and dynamic SQL Queries

---

core/aws_ddk_core/stages/glue_transform.py

**Enhancement**
Enhancing GlueTransform Stage for Stepfunction Crawler Task Retry
**Detail**
Added retries and backoff for the crawler task in step function so that it tries multiple time before failing, also instead of now catching the glue crawler running error and still succeeding the statemachine by design, it will now fail so CloudWatch can collect the right metric for alarm state
**Relates**
Enhancement: Enhancing GlueTransform Stage for Stepfunction Crawler Task Retry #206

Enhancing GlueTransform Stage for Stepfunction Crawler Task Retry

---

API.md
src/stages/appflow-ingestion.ts
test/appflow-ingestion-stage.test.ts

- Replacing Start Flow step with `CallAwsService` instead of using Custom State
- Checking status will have to remain a custom lambda for now as 
```bash
appflow describe-flow-execution-records
``` 
doesn’t have a parameter for execution and query is not supported by the Amazon States Language.
- #223 

feat: appflow stage refactor

---

API.md
src/pipelines/stage.ts
src/stages/kinesis-s3.ts
src/stages/sqs-lambda.ts
test/athena-sql-stage.test.ts
test/cicd-pipeline-stack.test.ts
test/data-pipelines.test.ts
test/sqs-lambda-stage.test.ts

feat: resource naming refactor

---

integ/integ.data-pipelines.assertions.test.ts
integ/src/lambda_write_s3/lambda_function.py
src/stages/sqs-lambda.ts

- Feature
Added an integration test where:
1. An S3 -> SQS -> Lambda pipeline is created
2. A data file is deposited to S3
3. The Lambda sends the message to an SQS queue
4. The integration test makes sure that the message is in the SQS queue
- https://github.com/awslabs/aws-ddk/issues/236

feat: Add data assertions for S3 -> SQS -> Lambda pipeline

---

API.md
CONTRIBUTING.md
src/cicd/pipelines.ts
src/config/configurator.ts
test/config.test.ts

We now have two ways of retrieving data from config.
1. Class method
```javascript
// Instantiate Config
const config = new Configurator({ configPath: "./ddk.yaml", environmentId: "dev" });
// Retrive Values from Object
config.getConfigAttribute("foo")
```
2. `static` method -- no object state 
```javascript
// Retrieve data directly from file
const config = Configurator.getEnvConfig({ configPath: "./test/test-config.yaml", environmentId: "dev" });
```

fix: move `getEnvConfig()` to static method

---

src/pipelines/stage.ts

Change default for 'state_machine_input' to undefined

fix: Change default for `state_machine_input` to undefined

---

API.md
src/cicd/actions.ts
src/cicd/pipelines.ts
test/cicd-pipeline-stack.test.ts

-  allowing command failure in generic actions like `Synth` & `Tests` to support different cdk language `beforeInstall` commands
- enforce `EnableKeyRotation` in pipeline kms key

feat: `CICDPipelineStack()` updates

---

API.md
src/stages/index.ts
src/stages/redshift-data-api.ts
test/redshift-data-api-stage.test.ts

- New Stage Redshift Data API
- Allows user to specify a list of sql commands to run against a redshift cluster via the `redshift-data` api. 
- Orchestrated by Step Functions
- Tested for functionality, however this should have an integration test as well which i've included as a subtask in #236 
- #201

feat: New Stage: Redshift Data API 

---

src/config/configurator.ts
test/config.test.ts

- Updates `Configurator()` functionality to update resources with paths matching specified `${id}/Resource`
- User will need to provide a subpath that matches a given resource's cdk metadata path but will not need to specify `/Resource` as this would override resource's that are created in addition to primary resources (e.g. Default Iam Policies, Event Sources etc)
An id of `Process Function` would match the following pattern and not the others.

chore: `Configurator()` resource id refactor

---

core/aws_ddk_core/resources/_glue.py
core/tests/unit/test_glue.py

- Bugfix
- Adds a check to avoid creating default glue security config is a custom one is provided.
- Adds a configuration parameter to `GlueFactory.job` function to configure name for default glue security config.
- Issue 1: If you use multiple environments and not parametrize glue job id by environment_id, the default security config that is created is not unique despite job_name being unique. Example 
```python
job1 = GlueFactory.job(
self, id=f"job-1",
environment_id=environment_id,
job_name=f"myproject-{self._environment_id}-job1",
....
)
```
This creates a security config with name `job-1-security-config`. If you use multiple environments, causes issues due to name not being unique. Relevant [code snippet](https://github.com/awslabs/aws-ddk/blob/main/core/aws_ddk_core/resources/_glue …

fix: Don't create default glue job security config if a custom one is passed.

---

cli/pyproject.toml
core/pyproject.toml
pyproject.toml

- Allows use of python 3.11.x with the AWS DDK. Unit tests and basic integration are passing using `3.11.1`
- Closes #288 

chore: incrementing upper bound python version -> `<3.12`

---

API.md
src/base/stack.ts
src/config/configurator.ts
src/core/glue-factory.ts
src/pipelines/pipelines.ts
src/pipelines/stage.ts
src/stages/databrew-transform.ts
src/stages/glue-transform.ts
src/stages/kinesis-s3.ts
src/stages/sqs-lambda.ts
test/appflow-ingestion-stage.test.ts
test/base-stack.test.ts
test/config.test.ts
test/data-pipelines.test.ts
test/databrew-transform-stage.test.ts
test/glue-transform-stage.test.ts
test/kinesis-s3-stage.test.ts
test/sqs-lambda-stage.test.ts

fix: Beta Testing Fixes

---

API.md
src/config/configurator.ts
test/config.test.ts
test/test-config.json

- Simplify CDK environment pull from config with:
- `getEnvironment()`
- `Configurator.getEnvironment()`

feat: `getEnvironment()`

---

src/base/stack.ts
src/config/configurator.ts
test/config.test.ts
test/test-config.json

feat: Add support for `RemovalPolicy` in config

---

.projen/tasks.json
API.md
src/config/configurator.ts

- change return type of `getEnvironment` to `cdk.Environment`
- Support use case of `CICDPipelineStack()`
```python
...
.add_stage(
stage_id="dev",
stage=ApplicationStage(
app,
"dev",
env=Configurator.get_environment(
config_path="./ddk.json", environment_id="dev"
),
),
)
```

chore: change return type of `getEnvironment` to `cdk.Environment`

---

docs/release/latest/how-to/ddk-configuration.markdown

- Documentation
- Fix language tabs
- Fix json config snippets

chore: Fix language tabs & config json in configurator how-to

---

API.md
src/cicd/actions.ts
src/cicd/pipelines.ts
test/cicd-pipeline-stack.test.ts

Fixes #130 
- Adds `failBuild` param to allow user to force codepipeline deployments to fail if CFNNag scans pick up violations.

fix: Adding failBuild parameter

---

src/base/stack.ts

fix: removing default `environmentId` from `getStackSynthesizer` method

---

.projen/deps.json
.projenrc.js
API.md
package.json
src/pipelines/stage.ts
src/stages/appflow-ingestion.ts
src/stages/athena-sql.ts
src/stages/databrew-transform.ts
src/stages/glue-transform.ts
src/stages/mwaa-trigger-dags.ts
src/stages/redshift-data-api.ts
test/base-stack.test.ts
test/sfn-stage.test.ts
test/test-sfn-config.json
yarn.lock

Allows for defining of SFN in three ways
1. `definition` : `stepfunction.IChainable` 
2. `definition` : `string` **JSON**
3. `definitionFile` : `string` **Path to JSON file**
These parameters are now conditionally optional meaning typescript would not allow for them to precede `props` in `createStateMachine()`. I think the best approach is to bring the parameters into the `StateMachineStageProps` interface.
#69

feat: Update `StateMachineStage` to use `definitionBody` instead of deprecated `definition`

---

.github/workflows/upgrade-main.yml
API.md
src/stages/glue-transform.ts
test/glue-transform-stage.test.ts

feat: make crawler optional in `GlueTransformStage()`

---

.projen/tasks.json
API.md
src/config/configurator.ts

Closes #416
Making `configPath` optional in interfaces:
- `GetTagsProps`
- `GetEnvironmentProps`

fix: Making 'configPath' optional in interfaces 

---

src/stages/mwaa-trigger-dags.ts

Currently, MWAATriggerDagStage does not pass the sfn event to the MWAA dag. This enhancement enables to pass runtime parameters/sfn event when triggering dag. The parameters can be accessed from the dag_run.conf.  
Changes made to MWAATriggerDagStage:
1) Trigger dag lambda has an additional payload of the sfn event passed in body
2) airflow command updated to pass sfn event to MWAA dag using --conf   
#428

feat: Update MWAATriggerDagsStage to pass json event to MWAA airflow dag

---

src/core/mwaa-environment.ts
test/mwaa-environment.test.ts

Description
Currently,ddk fails to deploy multiple MWAAEnvironment as VPC and MWAAExecutionRole have fixed ids.
Changes Made
VPC and MWAAExecutionRole have resource_prefox / props.name added to their id to ensure new resources are created for each MWAAEnvironment. 
Related Issue
#438

fix: update Update MWAAEnviroment to create VPC and MWAAExecutionRole with resource prefix

---

src/core/mwaa-environment.ts

Using MWAA Environment with `createVpc()` sometimes results in an invalid subnet amount error.
```
#/NetworkConfiguration/SubnetIds: expected maximum item count: 2, found: 3
```
Restricting MWAA creation to two private subnets per [AWS::MWAA::Environment NetworkConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mwaa-environment-networkconfiguration.html)

fix: Restrict MWAA Env to Two Subnets

---

.github/workflows/upgrade-main.yml
.projenrc.js

I feel like we don't need to have our dependencies upgrading daily, especially as our release candency approx. monthly 😄

chore: Reduce dependency upgrade frequency to weekly
